version: '3'
services:
  omniserver:
    image: geontech/redhawk-omniserver:2.0.6
    networks:
      - sdrnet
  domain:
    image: geontech/redhawk-domain:2.0.6
    volumes:
      - sdrroot:/var/redhawk/sdr
    env_file:
      - rh.env
    networks:
      - sdrnet
  gpp:
    image: geontech/redhawk-gpp:2.0.6
    env_file:
      - rh.env
    deploy:
      mode: global
    networks:
      - sdrnet
  usrp-b200:
    image: geontech/redhawk-usrp:2.0.6
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
    env_file:
      - rh.env
    environment:
      - USRP_TYPE=b200
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.usrp-b200 == true
    networks:
      - sdrnet
  rtlsdr:
    image: geontech/redhawk-rtl2832u:2.0.6
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
    env_file:
      - rh.env
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.rtlsdr == true
    networks:
      - sdrnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - sdrnet
volumes:
  sdrroot:
networks:
  sdrnet:
