version: '3'
services:
  omniserver:
    image: geontech/redhawk-omniserver:2.0.6
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - sdrnet
  domain:
    image: geontech/redhawk-domain:2.0.6
    depends_on:
      - omniserver
    volumes:
      - sdrroot:/var/redhawk/sdr
    env_file:
      - rh.env
    networks:
      - sdrnet
  gpp:
    image: geontech/redhawk-gpp:2.0.6
    depends_on:
      - omniserver
      - domain
    env_file:
      - rh.env
    deploy:
      mode: global
    networks:
      - sdrnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - sdrnet
volumes:
  sdrroot:
networks:
  sdrnet:
